apiVersion: batch/v1
kind: Job
metadata:
  name: secondb
spec:
  template:
    spec:
      containers:
      - name: secondb
        image: bitnami/postgresql:latest
        command: ["createdb"]
        args: ["-h","{{  .Values.database.hostname }}", "-U", "$(POSTGRES_USERNAME)", "atlassian" ]
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-auth
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: mysql-auth
      restartPolicy: Never