apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-auth
  namespace: atlassian
spec:  
  refreshInterval: 10m
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore    
  target:
    name: mysql-auth
  data:
  - secretKey: username
    remoteRef:
      key: {{ .Values.secretStoreName }}
      property: db_username
  - secretKey: password
    remoteRef:
      key: {{ .Values.secretStoreName }}
      property: db_password      