apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.commonLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "common.names.fullname" . }}
  selector:
    matchLabels:
      {{- include "common.labels.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config-jvm: {{ include (print $.Template.BasePath "/config-jvm.yaml") . | sha256sum }}
        {{- if .Values.fluentd.enabled }}
        checksum/config-fluentd: {{ include (print $.Template.BasePath "/configmap-fluentd.yaml") . | sha256sum }}
        {{- end }}
        {{- include "atlassian.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "common.labels.selectorLabels" . | nindent 8 }}
        {{- include "atlassian.podLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "atlassian.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.atlassian.shutdown.terminationGracePeriodSeconds }}
      {{- if .Values.atlassian.securityContextEnabled }}
      {{- with .Values.atlassian.securityContext }}
      securityContext:
        {{/* this condition will be removed in v2.0.0 */}}
        {{- if and .enabled .gid }}
        fsGroup: {{ .gid }}
        {{- else }}
        {{ toYaml . | nindent 8 }}
        {{- if not .fsGroup }}
        fsGroup: 2002
        {{- end }}
        {{- end }}
      {{- end }}
      {{- end }}
      hostAliases:
        {{- include "atlassian.additionalHosts" . | nindent 8 }}
      initContainers:
        {{- include "atlassian.additionalInitContainers" . | nindent 8 }}
        {{- if .Values.volumes.sharedHome.nfsPermissionFixer.enabled }}
        - name: nfs-permission-fixer
          image: {{ .Values.volumes.sharedHome.nfsPermissionFixer.imageRepo }}:{{ .Values.volumes.sharedHome.nfsPermissionFixer.imageTag }}
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0 # make sure we run as root so we get the ability to change the volume permissions
          volumeMounts:
            - name: shared-home
              mountPath: {{ .Values.volumes.sharedHome.nfsPermissionFixer.mountPath | quote }}
              {{- if .Values.volumes.sharedHome.subPath }}
              subPath: {{ .Values.volumes.sharedHome.subPath | quote }}
              {{- end }}
          command: ["sh", "-c", {{ include "sharedHome.permissionFix.command" . | quote }}]
        {{- end }}
        {{- include "common.jmx.initContainer" . | nindent 8 }}
      containers:
        - name: atlassian
          image: {{ include "atlassian.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.atlassian.ports.http }}
              protocol: TCP
            - name: hazelcast
              containerPort: {{ .Values.atlassian.ports.hazelcast }}
              protocol: TCP
            {{- include "common.jmx.port" . | nindent 12 }}
            {{- include "atlassian.additionalPorts" . | nindent 12 }}
          readinessProbe:
            httpGet:
              port: {{ .Values.atlassian.ports.http }}
              path: {{ .Values.atlassian.service.contextPath }}/status
            initialDelaySeconds: {{ .Values.atlassian.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.atlassian.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.atlassian.readinessProbe.failureThreshold }}
          {{- with .Values.atlassian.containerSecurityContext}}
          securityContext:
          {{- toYaml . | nindent 12}}
          {{- end}}
          {{- with .Values.atlassian.resources.container }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- include "atlassian.volumeMounts" . | nindent 12 }}
            {{- include "common.jmx.config.volumeMounts" . | nindent 12 }}
            {{- include "atlassian.additionalVolumeMounts" . | nindent 12 }}
            {{- include "atlassian.additionalLibraries" . | nindent 12 }}
            {{- include "atlassian.additionalBundledPlugins" . | nindent 12 }}
            {{- range $i, $n := .Values.additionalFiles }}
            - name: {{ .name }}-{{$i}}
              mountPath: {{ .mountPath }}/{{ .key }}
              subPath: {{ .key }}
            {{ end }}
          env:
            {{ if .Values.ingress.https }}
            - name: ATL_TOMCAT_SCHEME
              value: "https"
            - name: ATL_TOMCAT_SECURE
              value: "true"
            {{ end }}
            {{ if .Values.atlassian.service.contextPath }}
            - name: ATL_TOMCAT_CONTEXTPATH
              value: {{ .Values.atlassian.service.contextPath | quote }}
            {{ end }}
            - name: ATL_TOMCAT_PORT
              value: {{ .Values.atlassian.ports.http | quote }}
            {{ if .Values.ingress.host }}
            - name: ATL_PROXY_NAME
              value: {{ .Values.ingress.host | quote }}
            - name: ATL_PROXY_PORT
              value: {{ include "atlassian.ingressPort" . | quote }}
            {{ end }}
            - name: ATL_TOMCAT_ACCESS_LOG
              value: {{ .Values.atlassian.accessLog.enabled | quote }}
            - name: UMASK
              value: {{ .Values.atlassian.umask | quote }}
            - name: SET_PERMISSIONS
              value: {{ .Values.atlassian.setPermissions | quote }}
            - name: ATL_PRODUCT_HOME_SHARED
              value: {{ .Values.volumes.sharedHome.mountPath | quote }}
            - name: JVM_SUPPORT_RECOMMENDED_ARGS
              valueFrom:
                configMapKeyRef:
                  key: additional_jvm_args
                  name: {{ include "common.names.fullname" . }}-jvm-config
            {{- include "atlassian.clusteringEnvVars" . | nindent 12 }}
            {{- include "atlassian.databaseEnvVars" . | nindent 12 }}
            {{ with .Values.atlassian.license.secretName }}
            - name: ATL_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: {{ $.Values.atlassian.license.secretKey }}
            {{ end }}
            - name: JVM_MINIMUM_MEMORY
              valueFrom:
                configMapKeyRef:
                  key: min_heap
                  name: {{ include "common.names.fullname" . }}-jvm-config
            - name: JVM_MAXIMUM_MEMORY
              valueFrom:
                configMapKeyRef:
                  key: max_heap
                  name: {{ include "common.names.fullname" . }}-jvm-config
            - name: JVM_RESERVED_CODE_CACHE_SIZE
              valueFrom:
                configMapKeyRef:
                  key: reserved_code_cache
                  name: {{ include "common.names.fullname" . }}-jvm-config
            {{- include "atlassian.additionalEnvironmentVariables" . | nindent 12 }}
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", {{ .Values.atlassian.shutdown.command | quote }}]
        {{- include "fluentd.container" . | nindent 8 }}
        {{- include "atlassian.additionalContainers" . | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.atlassian.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName  | quote }}
      {{- end }}
      volumes:
        {{- range $i, $n := .Values.additionalFiles }}
        - name: {{ .name }}-{{$i}}
          {{ .type }}:
            {{ if hasPrefix .type "secret" }}{{ .type}}Name{{ else }}name{{ end }}: {{ .name }}
            items:
              - key: {{ .key }}
                path: {{ .key }}
        {{ end }}
        {{ include "atlassian.volumes" . | nindent 8 }}
        {{ include "fluentd.config.volume" . | nindent 8 }}
        {{ include "common.jmx.config.volume" . | nindent 8 }}
  {{ include "atlassian.volumeClaimTemplates" . | nindent 2 }}
