---      
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: elk-auth
  namespace: bitbucket
spec:  
  refreshInterval: 10m
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore    
  target:
    name: elk-auth-secret
  data:
  - secretKey: username
    remoteRef:
      key: {{ .Values.secretStoreName }}
      property: es_username
  - secretKey: password
    remoteRef:
      key: {{ .Values.secretStoreName }}
      property: es_password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bitbucket-auth
  namespace: bitbucket
spec:  
  refreshInterval: 10m
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore    
  target:
    name: bitbucket-auth
  data:
  - secretKey: username
    remoteRef:
      key: {{ .Values.secretStoreName }}
      property: bitbucket_username
  - secretKey: password
    remoteRef:
      key: {{ .Values.secretStoreName }}
      property: bitbucket_password      
  - secretKey: displayName
    remoteRef:
      key: {{ .Values.secretStoreName }}
      property: bitbucket_displayName
  - secretKey: emailAddress
    remoteRef:
      key: {{ .Values.secretStoreName }}
      property: bitbucket_emailAddress
---      
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-auth
  namespace: bitbucket
spec:  
  refreshInterval: 10m
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore    
  target:
    name: mysql-auth
  data:
  - secretKey: username
    remoteRef:
      key: {{ .Values.secretStoreName }}
      property: db_username
  - secretKey: password
    remoteRef:
      key: {{ .Values.secretStoreName }}
      property: db_password      