{{- if .Values.volumes.sharedHome.persistentVolumeClaim.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.names.fullname" . }}-shared-home
  labels:
  {{- include "common.labels.commonLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""  
  volumeName: confluence-shared-home  
  {{- with .Values.volumes.sharedHome.persistentVolumeClaim.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end }}
