annotations:
  artifacthub.io/changes: |-
    - "Run jmx init container as root: get fix from common chart ver 1.2.3 (#608)"
    - "Swap ingress paths for priority based rules (#602)"
  artifacthub.io/containsSecurityUpdates: "true"
apiVersion: v2
appVersion: 7.19.10
dependencies:
- name: common
  repository: https://atlassian.github.io/data-center-helm-charts
  version: 1.2.3
description: A chart for installing Confluence Data Center on Kubernetes
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/confluence.svg
keywords:
- Confluence
- Confluence Server
- Confluence Data Center
- Confluence DC
- Atlassian
kubeVersion: '>=1.21.x-0'
name: confluence
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-atlassian-confluence-server/
type: application
version: 1.13.1
