---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: elk-auth
  namespace: elastic
spec:  
  refreshInterval: 10m
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore    
  target:
    name: elk-auth-secret
  data:
  - secretKey: username
    remoteRef:
      key: SecretsStore
      property: es_username
  - secretKey: password
    remoteRef:
      key: SecretsStore
      property: es_password 
